dataSources:
  member_master:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://crm.mysqlw.emr.com:3306/shardingdemo1?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: emr.2022
  member_slave:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://crm.mysqlw.emr.com:3306/shardingdemo1?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: emr.2022
  info_master:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://crm.mysqlw.emr.com:3306/shardingdemo2?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: emr.2022
  info_slave:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://crm.mysqlw.emr.com:3306/shardingdemo2?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: emr.2022
rules:
  - !READWRITE_SPLITTING
    dataSources:
      readwrite_member:
        staticStrategy:
          writeDataSourceName: member_master
          readDataSourceNames:
            - member_slave
        loadBalancerName: round_robin
      readwrite_info:
        staticStrategy:
          writeDataSourceName: info_master
          readDataSourceNames:
            - info_slave
        loadBalancerName: round_robin
    loadBalancers:
      round_robin:
        type: ROUND_ROBIN


props:
  sql-show: true
  sql-federation-type: ORIGINAL

