spring:
  application:
    name: sharding-demo
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardinsphere-config.yaml
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.evercare
  configLocation: classpath:mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  row-bounds-with-count: true